---
name: CI

on:
  merge_group:
  push:
    branches: [master, main, ci-*]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

permissions: {}

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - uses: hynek/setup-cached-uv@v2
      - run: |
          npm install
          echo "$(pwd)/node_modules/.bin" >> "$GITHUB_PATH"

      - name: Prepare tox
        run: |
          V=${{ matrix.python-version }}
          echo TOX_PYTHON=py"$(echo $V | tr -d.)" >>"$GITHUB_ENV"

      - run: >
          uvx --with=tox-uv
          tox run
          -e ${{ env.TOX_PYTHON }}
